#!/bin/bash
# uses a custom modular JRE to run the application uberjar
# from ogri-la/strongbox-appimage at 5119f26. Copyright © Torkus 2023 - present, AGPL-3.0.
set -e
DIR="$(dirname "$(readlink -f "$0")")"
cd $DIR
unset LD_LIBRARY_PATH # strongbox/issues/441: avoid conflicts with host .so files
./usr/bin/java -jar ./usr/app.jar "$@"
